def christmasTree(): 
    print(u'\u001b[32m            *            ')
    print('                         ')
    print('          * * *          ')
    print('                         ')
    print('        * * * * *        ')
    print('                         ')
    print('      * * * * * * *      ')
    print('                         ')
    print('    * * * * * * * * *    ')
    print('                         ')
    print('  * * * * * * * * * * *  ')
    print('                         ')
    print('* * * * * * * * * * * * *')
    print('                         ')
    print(u'\u001b[33m           ***           ')
    print('                         ')
    print(u'           ***           \u001b[0m')
  